--
- hosts: 127.0.0.1
  connection: local
  vars:
    project_root: .
  roles:
    - ssh-local

- hosts: all
  gather_facts: yes
  roles:
    - common
    - mesos-common

- hosts: role=master
  gather_facts: yes
  roles:
    - mesos-master

- hosts: role=slave
  gather_facts: yes
  roles:
    - mesos-slave