---
- name: install mesos
  sudo: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mesos

- name: copy zk conf for mesos
  sudo: yes
  template:
    src: zk.j2
    dest: /etc/mesos/zk

- name: copy mesos-master conf
  sudo: yes
  template:
    src: mesos-master.j2
    dest: /etc/default/mesos-master

- name: start mesos-master
  sudo: yes
  service:
    name: mesos-master
    state: started